config/routes.rb
Dyalikeblags::Engine.routes.draw do

  
	root 'public/posts#index'

  namespace :dashboard do
    resources :posts
    resources :static_pages
    resources :images
    resources :users
    end

  namespace :public do
    resources :posts
    resources :static_pages, only: [:show], param: :title_bar
  end


end

app/models/dyalikeblags/dashboard.rb
module Dyalikeblags
  module Dashboard
    def self.table_name_prefix
      'dyalikeblags_dashboard_'
    end
  end
end

app/models/dyalikeblags/post.rb
module Dyalikeblags
  class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments
  end
end

app/controllers/dyalikeblags/dashboard/images_controller.rb
require_dependency "dyalikeblags/dashboard_controller"

module Dyalikeblags
  class Dashboard::ImagesController < DashboardController
    before_action :set_image, only: [:show, :edit, :update, :destroy]

    # GET /images
    def index
      @images = Image.all
    end

    # GET /images/1
    def show
    end

    # GET /images/new
    def new
      @image = Image.new
    end

    # GET /images/1/edit
    def edit
    end

    # POST /images
    def create

      Image.upload( params[:image][:image_file]  )

      @image = Image.new
      @image.name = params[:image][:name]
      @image.file_name = params[:image][:image_file].original_filename



      if @image.save
        redirect_to [:dashboard, @image], notice: 'Image was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /images/1
    def update
      if @image.update(image_params)
        redirect_to [:dashboard, @image], notice: 'Image was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /images/1
    def destroy
      @image.destroy
      redirect_to dashboard_images_path, notice: 'Image was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_image
        @image = Image.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def image_params
        params.require(:image).permit(:file_name, :name)
      end
  end
end

app/controllers/dyalikeblags/dashboard/posts_controller.rb
require_dependency "dyalikeblags/dashboard_controller"

module Dyalikeblags
  class Dashboard::PostsController < DashboardController

		  before_action :set_post, only: [:show, :edit, :update, :destroy]
		  
		  # GET /posts
		  # GET /posts.json
		  def index
		    @posts = Dyalikeblags::Post.all
		  end

		  # GET /posts/1
		  # GET /posts/1.json
		  def show
		    #@post = Dyalikeblags::Post.find(params[:id])
    	end

		  # GET /posts/new
		  def new
		    @post = Dyalikeblags::Post.new
		    @image_names = Dyalikeblags::Image.all.map{|u| [ u.name ] }
		  end

		  # GET /posts/1/edit
		  def edit
		  end

		  # POST /posts
		  # POST /posts.json
		  def create

		    #create new post
		    @post = Dyalikeblags::Post.new( post_params() )
		    @post.image = Dyalikeblags::Image.where(name: @post.image ).take.file_name
		    
		    #add image file name to new post
		    
		      if @post.save
						redirect_to [:dashboard, @post], notice: 'Post was successfully created.' 
		      else
		        render :action => :new
		      end

		  end

		  # PATCH/PUT /posts/1
		  # PATCH/PUT /posts/1.json
		  def update

		      if @post.update( post_params() )
		        redirect_to [:dashboard, @post], notice: 'Post was successfully updated.' 
		      else
		        render :action => :edit 
		      end
		  end

		  # DELETE /posts/1
		  # DELETE /posts/1.json
		  def destroy
		    @post.destroy
					redirect_to dashboard_posts_path, notice: 'Post was successfully destroyed.' 
			  end

		  private
		    # Use callbacks to share common setup or constraints between actions.
		    def set_post
		      @post = Dyalikeblags::Post.find(params[:id])
		    end

		    # Never trust parameters from the scary internet, only allow the white list through.
		    def post_params
		      params.require(:post).permit(:title, :content, :user_id, :image, :user_id)
		    end


  end
end

app/controllers/dyalikeblags/dashboard/static_pages_controller.rb
require_dependency "dyalikeblags/dashboard_controller"

module Dyalikeblags
  class Dashboard::StaticPagesController < DashboardController
    before_action :set_static_page, only: [:show, :edit, :update, :destroy]

    # GET /static_pages
    def index
      @static_pages = Dyalikeblags::StaticPage.all
    end

    # GET /static_pages/1
    def show
    end

    # GET /static_pages/new
    def new
      @static_page = Dyalikeblags::StaticPage.new
    end

    # GET /static_pages/1/edit
    def edit
    end

    # POST /static_pages
    def create
      @static_page = Dyalikeblags::StaticPage.new( static_page_params() )

      if @static_page.save
        redirect_to  [:dashboard, @static_page], notice: 'Static page was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /static_pages/1
    def update
      if @static_page.update( static_page_params() )
        redirect_to [:dashboard, @static_page], notice: 'Static page was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /static_pages/1
    def destroy
      @static_page.destroy
      redirect_to dashboard_static_pages_path, notice: 'Static page was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_static_page
        @static_page = Dyalikeblags::StaticPage.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def static_page_params
        params.require(:static_page).permit(:title_bar, :static_content)
      end
  end
end

app/controllers/dyalikeblags/dashboard/users_controller.rb
require_dependency "dyalikeblags/dashboard_controller"

module Dyalikeblags
  class Dashboard::UsersController < DashboardController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    def index
      @users = ::User.all
    end


 
    # GET /users/1
    def show
    end


    # GET /users/new
    def new
      @user = ::User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    def create
      @user = ::User.new(user_params)

      if @user.save
        redirect_to [:dashboard, @user], notice: 'User was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /users/1
    def update
      if @user.update(user_params)
        redirect_to [:dashboard, @user], notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /users/1
    def destroy
      @user.destroy
      redirect_to dashboard_users_path, notice: 'User was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = ::User.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def user_params
        params.require(:user).permit(:email, :username, :password, :password_confirmation) 
      end
end
end

app/controllers/dyalikeblags/dashboard_controller.rb
module Dyalikeblags
  class DashboardController < ::ApplicationController
  	before_action :authenticate_user!
  	layout "dyalikeblags/dashboard"
  end
end

app/helpers/dyalikeblags/dashboard/posts_helper.rb
module Dyalikeblags
  module Dashboard::PostsHelper
  end
end

app/helpers/dyalikeblags/posts_helper.rb
module Dyalikeblags
  module PostsHelper
  end
end

app/views/clutter/dashboard/posts/_form.html.erb
<%= form_for [:dashboard, @post] do |f| %>
<div class="row">
<div class= "col-md-12">
 


  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_area :title, class: "form-control", rows: "1" %>
    </div>

    <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control", rows: "10%" %>
    </div>

    <div class="form-group">
   <%# f.hidden_field :user_id, :value => current_user.id %>

    <%= f.hidden_field :user_id, :value => 1 %>
    <%= f.hidden_field :image %>

    <%= f.label :image %><br>
    <%= f.file_field :image_file  %>
    </div>

    <%= f.submit class: "btn btn-default" %>


</div>
</div>
<% end %>

app/views/clutter/dashboard/posts/edit.html.erb
<%= render 'form' %>

<%# link_to 'Show', @post %> 

app/views/clutter/dashboard/posts/index.html.erb
 <% @posts.each do |post| %>
    

  <%# render partial: "shared/dashboard/index_single", locals: {post: post} %>

  <div class ="row">
		  <%#link_to 'Edit', edit_dashboard_post_path(post)  %>  | 
			<%#link_to 'Delete', dashboard_post_path(post), :confirm=>"Are you sure?",  :method => :delete %> 
	</div>


 <% end %>

app/views/clutter/dashboard/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/clutter/dashboard/posts/show.html.erb
      <div class="row  custom_index_row">

      <div class="row">
        <div class="col-md-12">
        <h4>
          <div style="text-decoration:underline">
          <%=  @post.title %>
          </div>

            <%= @post.created_at.to_date %> 
              By: <%= @post.user_id %> 
        </h4>


            

        </div>
      </div>
        

        <div class="row">
        <div class="col-md-12">

          <div><%= image_tag @post.image ,class: "img-rounded", style: "border:1px black solid; float:left; margin-right:20px",  width: '20%', height: 'auto' %>
          </div>
        
          <div class ="custom_body_column">
              <%=  simple_format(@post.content) %>
          </div>
        
        </div>
        </div>
    

      </div>
<%#link_to 'Edit', edit_post_path(@post) %> 