config/routes.rb
Dyalikeblags::Engine.routes.draw do

  
	root 'public/posts#index'

  namespace :dashboard do
    resources :posts
    resources :static_pages
    resources :images
    resources :users
    end

  namespace :public do
    resources :posts
    resources :static_pages, only: [:show], param: :title_bar
  end


end

app/models/dyalikeblags/dashboard.rb
module Dyalikeblags
  module Dashboard
    def self.table_name_prefix
      'dyalikeblags_dashboard_'
    end
  end
end

app/controllers/dyalikeblags/dashboard/images_controller.rb
require_dependency "dyalikeblags/dashboard_controller"

module Dyalikeblags
  class Dashboard::ImagesController < DashboardController
    before_action :set_image, only: [:show, :edit, :update, :destroy]

    # GET /images
    def index
      @images = Image.all
    end

    # GET /images/1
    def show
    end

    # GET /images/new
    def new
      @image = Image.new
    end

    # GET /images/1/edit
    def edit
    end

    # POST /images
    def create

      Image.upload( params[:image][:image_file]  )

      @image = Image.new
      @image.name = params[:image][:name]
      @image.file_name = params[:image][:image_file].original_filename



      if @image.save
        redirect_to [:dashboard, @image], notice: 'Image was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /images/1
    def update
      if @image.update(image_params)
        redirect_to [:dashboard, @image], notice: 'Image was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /images/1
    def destroy
      @image.destroy
      redirect_to dashboard_images_path, notice: 'Image was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_image
        @image = Image.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def image_params
        params.require(:image).permit(:file_name, :name)
      end
  end
end

app/controllers/dyalikeblags/dashboard/posts_controller.rb
require_dependency "dyalikeblags/dashboard_controller"

module Dyalikeblags
  class Dashboard::PostsController < DashboardController

		  before_action :set_post, only: [:show, :edit, :update, :destroy]
		  
		  # GET /posts
		  # GET /posts.json
		  def index
		    @posts = Dyalikeblags::Post.all
		  end

		  # GET /posts/1
		  # GET /posts/1.json
		  def show
		    #@post = Dyalikeblags::Post.find(params[:id])
    	end

		  # GET /posts/new
		  def new
		    @post = Dyalikeblags::Post.new
		    @image_names = Dyalikeblags::Image.all.map{|u| [ u.name ] }
		  end

		  # GET /posts/1/edit
		  def edit
		  end

		  # POST /posts
		  # POST /posts.json
		  def create

		    #create new post
		    @post = Dyalikeblags::Post.new( post_params() )
		    @post.image = Dyalikeblags::Image.where(name: @post.image ).take.file_name
		    
		    #add image file name to new post
		    
		      if @post.save
						redirect_to [:dashboard, @post], notice: 'Post was successfully created.' 
		      else
		        render :action => :new
		      end

		  end

		  # PATCH/PUT /posts/1
		  # PATCH/PUT /posts/1.json
		  def update

		      if @post.update( post_params() )
		        redirect_to [:dashboard, @post], notice: 'Post was successfully updated.' 
		      else
		        render :action => :edit 
		      end
		  end

		  # DELETE /posts/1
		  # DELETE /posts/1.json
		  def destroy
		    @post.destroy
					redirect_to dashboard_posts_path, notice: 'Post was successfully destroyed.' 
			  end

		  private
		    # Use callbacks to share common setup or constraints between actions.
		    def set_post
		      @post = Dyalikeblags::Post.find(params[:id])
		    end

		    # Never trust parameters from the scary internet, only allow the white list through.
		    def post_params
		      params.require(:post).permit(:title, :content, :user_id, :image, :user_id)
		    end


  end
end

app/controllers/dyalikeblags/dashboard/static_pages_controller.rb
require_dependency "dyalikeblags/dashboard_controller"

module Dyalikeblags
  class Dashboard::StaticPagesController < DashboardController
    before_action :set_static_page, only: [:show, :edit, :update, :destroy]

    # GET /static_pages
    def index
      @static_pages = Dyalikeblags::StaticPage.all
    end

    # GET /static_pages/1
    def show
    end

    # GET /static_pages/new
    def new
      @static_page = Dyalikeblags::StaticPage.new
    end

    # GET /static_pages/1/edit
    def edit
    end

    # POST /static_pages
    def create
      @static_page = Dyalikeblags::StaticPage.new( static_page_params() )

      if @static_page.save
        redirect_to  [:dashboard, @static_page], notice: 'Static page was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /static_pages/1
    def update
      if @static_page.update( static_page_params() )
        redirect_to [:dashboard, @static_page], notice: 'Static page was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /static_pages/1
    def destroy
      @static_page.destroy
      redirect_to dashboard_static_pages_path, notice: 'Static page was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_static_page
        @static_page = Dyalikeblags::StaticPage.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def static_page_params
        params.require(:static_page).permit(:title_bar, :static_content)
      end
  end
end

app/controllers/dyalikeblags/dashboard/users_controller.rb
require_dependency "dyalikeblags/dashboard_controller"

module Dyalikeblags
  class Dashboard::UsersController < DashboardController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    def index
      @users = ::User.all
    end


 
    # GET /users/1
    def show
    end


    # GET /users/new
    def new
      @user = ::User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    def create
      @user = ::User.new(user_params)

      if @user.save
        redirect_to [:dashboard, @user], notice: 'User was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /users/1
    def update
      if @user.update(user_params)
        redirect_to [:dashboard, @user], notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /users/1
    def destroy
      @user.destroy
      redirect_to dashboard_users_path, notice: 'User was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = ::User.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def user_params
        params.require(:user).permit(:email, :username, :password, :password_confirmation) 
      end
end
end

app/controllers/dyalikeblags/dashboard_controller.rb
module Dyalikeblags
  class DashboardController < ::ApplicationController
  	before_action :authenticate_user!
  	layout "dyalikeblags/dashboard"
  end
end

app/helpers/dyalikeblags/dashboard/posts_helper.rb
module Dyalikeblags
  module Dashboard::PostsHelper
  end
end

app/views/clutter/shared/dashboard/_dashboard.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://getbootstrap.com/examples/dashboard/#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="http://getbootstrap.com/examples/dashboard/#">Dashboard</a></li>
            <li><a href="http://getbootstrap.com/examples/dashboard/#">Settings</a></li>
            <li><a href="http://getbootstrap.com/examples/dashboard/#">Profile</a></li>
            <li><a href="http://getbootstrap.com/examples/dashboard/#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="http://getbootstrap.com/examples/dashboard/#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="http://getbootstrap.com/examples/dashboard/#">Reports</a></li>
            <li><a href="http://getbootstrap.com/examples/dashboard/#">Analytics</a></li>
            <li><a href="http://getbootstrap.com/examples/dashboard/#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjxnPjx0ZXh0IHg9Ijc0LjA1NDY4NzUiIHk9IjEwMCIgc3R5bGU9ImZpbGw6I0ZGRkZGRjtmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMHB0O2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjIwMHgyMDA8L3RleHQ+PC9nPjwvc3ZnPg==" data-holder-rendered="true">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzM5REJBQyIvPjxnPjx0ZXh0IHg9Ijc0LjA1NDY4NzUiIHk9IjEwMCIgc3R5bGU9ImZpbGw6IzFFMjkyQztmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMHB0O2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjIwMHgyMDA8L3RleHQ+PC9nPjwvc3ZnPg==" data-holder-rendered="true">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjxnPjx0ZXh0IHg9Ijc0LjA1NDY4NzUiIHk9IjEwMCIgc3R5bGU9ImZpbGw6I0ZGRkZGRjtmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMHB0O2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjIwMHgyMDA8L3RleHQ+PC9nPjwvc3ZnPg==" data-holder-rendered="true">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzM5REJBQyIvPjxnPjx0ZXh0IHg9Ijc0LjA1NDY4NzUiIHk9IjEwMCIgc3R5bGU9ImZpbGw6IzFFMjkyQztmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMHB0O2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjIwMHgyMDA8L3RleHQ+PC9nPjwvc3ZnPg==" data-holder-rendered="true">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

app/views/clutter/shared/dashboard/_index_single.html.erb
  <div class="row  custom_index_row">



      <div class="row">
        <div class="col-md-12">
          <div style="text-decoration:underline">
          post.title
          <%# link_to post.title, dashboard_post_path(post) %>
          </div>
         
        </div>
      </div>
        

        <div class="row">
          <div class="col-md-1"><%= image_tag post.image ,class: "img-thumbnail" %></div>
          <div class="col-md-11 custom_body_column">
         
              <%= truncate simple_format(post.content), length: 390 %>
           
          </div>
        </div>

          <div class="row">
           <div class="col-md-12">

              <%= post.created_at.to_date %> <br/>
              By User: <%= post.user_id %> 
            </div> 
          </div> 

  </div>

app/views/clutter/shared/dashboard/_navbar.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">

        <div class="navbar-header">
          <a class="navbar-brand" href="<%= public_posts_path %>">Transient Design</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">


  

            <li>
              <p class="navbar-text">Hello <%#current_user.email %> </p>
            </li>

            <li>
              <%#link_to "Sign out", destroy_user_session_path, :method => :delete %>
            </li>


          </ul>
        </div>

      </div>
    </nav>

app/views/clutter/shared/dashboard/_sidebar.html.erb
          <ul class="nav nav-sidebar">

            <form class="navbar-form">
		            <input type="text" class="form-control" placeholder="Search...">
		         </form>
		         
          	<li><%#link_to "All Posts", dashboard_posts_path%></li>
          	<li><%#link_to "New Post", new_dashboard_post_path%></li>
          </ul>

S